
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: loginfacebook_development


test:
  <<: *default
  database: loginfacebook_test

production:
  <<: *default
  database: loginfacebook
  username: nam
  password: 123456
